Amazing Python Projects_Scripts/Mailing scripts/README.md
Amazing Python Projects_Scripts/Mailing scripts/mail-script.py
Amazing Python Projects_Scripts/mail-script.py

This pull request adds a mailing script that can help read a CSV file and parse the data to send mails automatedly using python.

Adding a python script to send mails automatedly

---

Web Dev Projects_or_Portfolios/Project_doc.md
Web Dev Projects_or_Portfolios/Stock Market Simulator/client/.gitignore
Web Dev Projects_or_Portfolios/Stock Market Simulator/client/package-lock.json
Web Dev Projects_or_Portfolios/Stock Market Simulator/client/package.json
Web Dev Projects_or_Portfolios/Stock Market Simulator/client/public/index.html
Web Dev Projects_or_Portfolios/Stock Market Simulator/client/public/manifest.json
Web Dev Projects_or_Portfolios/Stock Market Simulator/client/public/robots.txt
Web Dev Projects_or_Portfolios/Stock Market Simulator/client/src/App.css
Web Dev Projects_or_Portfolios/Stock Market Simulator/client/src/App.js
Web Dev Projects_or_Portfolios/Stock Market Simulator/client/src/App.test.js
Web Dev Projects_or_Portfolios/Stock Market Simulator/client/src/index.css
Web Dev Projects_or_Portfolios/Stock Market Simulator/client/src/index.js
Web Dev Projects_or_Portfolios/Stock Market Simulator/client/src/reportWebVitals.js
Web Dev Projects_or_Portfolios/Stock Market Simulator/client/src/setupTests.js

added stock market simulator in web dev projects and accordingly updated project_doc.md

added stock market simulator and updated project_doc.md

---

README.md
Web Dev Projects_or_Portfolios/CSS-Grid-Animated-Tiles-with-Toggle-switch/index.html
Web Dev Projects_or_Portfolios/CSS-Grid-Animated-Tiles-with-Toggle-switch/script.js
Web Dev Projects_or_Portfolios/CSS-Grid-Animated-Tiles-with-Toggle-switch/styles.css
Web Dev Projects_or_Portfolios/Project_doc.md

I have created a folder  Hacktoberfest2021_awesome-projects/Web Dev Projects_or_Portfolios/CSS-Grid-Animated-Tiles-with-Toggle-switch
I have updated the < project_doc.md > as well and also added my name to the Contributors list.
Please review my commits and merge my pull request.
If you find any bugs please let me know.

Added my Web Development project ( issue #8 )

---

Web Dev Projects_or_Portfolios/CSS-Grid-Animated-Tiles-with-Toggle-switch/readme.md

Although it's not my project then also I have updated the readme.md file.

Readme.md file updated

---

README.md
Unique C++ Projects/BinaryToDecimal.cpp

Contributing for Hacktoberfest 2021

Binary to Decimal convertor

---

Web Dev Projects_or_Portfolios/Age Calculator/index.html
Web Dev Projects_or_Portfolios/Age Calculator/index.js
Web Dev Projects_or_Portfolios/Age Calculator/readme.md
Web Dev Projects_or_Portfolios/Age Calculator/style.css
Web Dev Projects_or_Portfolios/Project_doc.md

Hey @TechSpiritSS @ron2111 👋
- I have added the age calculator project 
- Added readme.md file to the project
- Updated Project_doc.md file

🚀Added Age Calculator 

---

Amazing Python Projects_Scripts/Folder-Automator/automate_folder.py
Amazing Python Projects_Scripts/Project_doc.md

A Script that keeps you organized when you have a mess of files in your old downloads folder.

Added Script to Automate Folder Files and updated the necessary docs

---

Amazing Python Projects_Scripts/GUI calculator.py

It is GUI based calculator made using python inbuilt library Tkinter. For the time, it performs essential functions but new operations can be added easily, if required.

Added GUI based calculator

---

Web Dev Projects_or_Portfolios/Online Compiler/index.html
Web Dev Projects_or_Portfolios/Online Compiler/readme.md

This is a simple code editor created using HTML, CSS, Javascript, Judge0 api.
- Get the Judge0 api key from the link provided in the code.
- Specify the correct ids for different coding languages.
- Type the code in the online code compiler or editor.
- Click on "Run".
- An interactive output is shown to the user on the right side.
- The user can select any programming language from the drop-down list. 
I have contributed towards hacktoberfest'2021. Kindly review the code, accept my pr and add the tag.
@ron2111

Online Compiler

---

Web Dev Projects_or_Portfolios/Amazon-Prime-Login-Page-Clone/README.md
Web Dev Projects_or_Portfolios/Amazon-Prime-Login-Page-Clone/index.css
Web Dev Projects_or_Portfolios/Amazon-Prime-Login-Page-Clone/index.html

Made a HTML and CSS clone of amazon prime login page

Amazom Prime Video Login Page Clone

---

Basic Background Generator/Readme.md
Basic Background Generator/index.html
Basic Background Generator/script.js
Basic Background Generator/style.css

I have added a basic Background Gradient Generator Project using HTML, CSS, and JS for HacktoberFest.
Kindly Review.

Added Basic Background Generator Project

---

Unique C++ Projects/Recover JPG/recover.c

Project_doc.md File is missing in this

Recover jpg

---

Web Dev Projects_or_Portfolios/Current weather web app/index.html

I have added a footer to this page for contact purposes such as Facebook, WhatsApp, Instagram, etc.

Adding a Footer to this Page

---

Web Dev Projects_or_Portfolios/Current weather web app/style.css

Update size color etc of the footer added in the HTML section of this page.

Update the Styling for Footer

---

HTML projects/Calculator

Basic Calculator in HTML, will appreciate additions to this.

Basic Calculator

---

Amazing Python Projects_Scripts/quote_scrap.py

I have added a python script for scraping quotes from a website using bs4 and requests library.

quotes scraping using python script

---

ML Projects/Sentiment Analysis/Sentiment_Analysis.ipynb
ML Projects/Sentiment Analysis/readme.md

Added sentiment analysis project

added sentiment analysis project

---

Awesome Javascript Projects_Scripts/Password Creator/README.md
Awesome Javascript Projects_Scripts/Password Creator/app.js
Awesome Javascript Projects_Scripts/Password Creator/index.html
Awesome Javascript Projects_Scripts/Password Creator/style.css

Password Creator lets you generate random passwords of length that you enter.
It helps in setting random passwords for accounts wherever required.

Password Creator

---

.github/ISSUE_TEMPLATE/issue-form.yml
.github/PULL_REQUEST_TEMPLATE.md

- Added templates for the Issues and Pull Requests on this Repository
- It will help by:
Reducing Possibility of Spam Issues and Requests
Easier Visibility
Better Tracking of Issues and Pull Requests
- Fixes #383

[Improved]: Issues and Pull Requests

---

Awesome Javascript Projects_Scripts/Project_doc.md

I added My meditation app Project .

Added my project and Update Project_doc.md

---

ML Projects/Voice Assistant/Readme.md
ML Projects/Voice Assistant/speech.py

-Added Voice Assistant and Readme.md file
<hr>
<hr>
<hr>

Voice Assistant

---

ML Projects/Heart Disease Prediction using ML/Heart Disease Classification.ipynb
ML Projects/Heart Disease Prediction using ML/Readme.md

<hr>
-Added Heart Disease prediction using ML and Readme file
<hr>
<hr>

Heart Disease prediction using ML

---

Incredible Java Projects/Circle drawing applet/MidpointCircle.java
Incredible Java Projects/Circle drawing applet/readme.md

**_midpoint circle drawing algorithm added with readme.md file_**
contribute by - **Anirban Chand**

midpoint circle drawing algorithm added 

---

ML Projects/Spam Classifier using NLP/Readme.md
ML Projects/Spam Classifier using NLP/Spam_Classifier.py

<hr>
-Added Spam Classifier using NLP and Readme file
<hr>
<hr>

Spam Classifier using NLP

---

ML Projects/Chronic Kidney Disease prediction/Readme.md
ML Projects/Chronic Kidney Disease prediction/predicting-chronic-kidney-disease (1).ipynb

<hr>
-Added Chronic Kidney Disease prediction and readme file
<hr>
<hr>

Chronic Kidney Disease prediction

---

Unique C++ Projects/Minesweeper/minesweeper.cpp
Unique C++ Projects/Minesweeper/readme.md

<hr>
- The project is a recreation of the old minesweeper game with a command-line interface in C++.
<hr>
<hr>
<hr>
<hr>

Added Minesweeper Project

---

ML Projects/Phishing -Detection-Using-Machine-Learning/Model Evaluation.ipynb
ML Projects/Phishing -Detection-Using-Machine-Learning/README.md

<hr>
Added Phishing Detection Using Machine Learning Apporach
<hr>
<hr>
<hr>
<hr>

Added Phishing Detection Using Machine Learning

---

Amazing Python Projects_Scripts/Project_doc.md
Amazing Python Projects_Scripts/Transpose the Image/Image_Transpose.py

<hr>
- It would take the image and just transpose it according to your choice like left and right.
<hr>
<hr>
<hr>
<hr>

Transpose the Image

---

Unique C++ Projects/calculator using cpp/calc.cpp

<hr>
- Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
- Fixes #529 
<hr>
- [✔ ] C++ Projects
<hr>
- [✔] I follow Contributing Guidelines & Code of conduct of this project.
- [✔ ] I have performed a self-review of my own code or work.
- [ ✔] I have commented my code, particularly in hard-to-understand areas.
- [✔ ] My changes generates no new warnings.
<hr>
<hr>

updated code

---

ML Projects/Celcius to Fahrenheit/README.md
ML Projects/Celcius to Fahrenheit/celcius_to_fahrenheit.ipynb

<hr>
- im added convert celcius to fahrenheit using machine learning 
- Fixes # <issue_number_here> 
<hr>
<hr>
<hr>
<hr>

added convert celcius_to_fahrenheit using Machine Learning
